<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-626U24Q" name="com.adminlte.qa.testcases.AdduserTestcases" tests="4" failures="1" timestamp="2019-12-27T17:42:38 IST" time="80.070" errors="0">
  <testcase name="gettitleofpage" time="14.378" classname="com.adminlte.qa.testcases.AdduserTestcases">
    <failure type="java.lang.AssertionError" message="JavaByKiran | Add User expected:&lt;JavaByKiran | Add User&gt; but was:&lt;Actual name is differnt than Expected &gt;">
      <![CDATA[java.lang.AssertionError: JavaByKiran | Add User expected:<JavaByKiran | Add User> but was:<Actual name is differnt than Expected >
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:82)
at com.adminlte.qa.testcases.AdduserTestcases.gettitleofpage(AdduserTestcases.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettitleofpage -->
  <testcase name="createnewUserTest" time="21.528" classname="com.adminlte.qa.testcases.AdduserTestcases"/>
  <testcase name="createnewUserTest" time="23.652" classname="com.adminlte.qa.testcases.AdduserTestcases"/>
  <testcase name="createnewUserTest" time="20.512" classname="com.adminlte.qa.testcases.AdduserTestcases"/>
</testsuite> <!-- com.adminlte.qa.testcases.AdduserTestcases -->
