<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-626U24Q" name="com.adminlte.qa.testcases.AdduserTestcases" tests="4" failures="1" timestamp="27 Dec 2019 12:39:28 GMT" time="89.946" errors="0">
  <testcase name="gettitleofpage" time="17.625" classname="com.adminlte.qa.testcases.AdduserTestcases">
    <failure type="java.lang.AssertionError" message="JavaByKiran | Add User expected:&lt;JavaByKiran | Add User&gt; but was:&lt;Actual name is differnt than Expected &gt;">
      <![CDATA[java.lang.AssertionError: JavaByKiran | Add User expected:<JavaByKiran | Add User> but was:<Actual name is differnt than Expected >
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at com.adminlte.qa.testcases.AdduserTestcases.gettitleofpage(AdduserTestcases.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
    </failure>
  </testcase> <!-- gettitleofpage -->
  <testcase name="createnewUserTest" time="23.325" classname="com.adminlte.qa.testcases.AdduserTestcases"/>
  <testcase name="createnewUserTest" time="22.343" classname="com.adminlte.qa.testcases.AdduserTestcases"/>
  <testcase name="createnewUserTest" time="26.653" classname="com.adminlte.qa.testcases.AdduserTestcases"/>
</testsuite> <!-- com.adminlte.qa.testcases.AdduserTestcases -->
